sudo: false
language: node_js
node_js: 10
script:
- npm run lint
- npm run prepare
- npm test
deploy:
  provider: npm
  on:
    tags: true
  api_key:
    secure: QDNCeFC7uv6cJP/NrvLVXaT/juuWyzNoI2OkmN/+OvIoe44LYvkYwDZoM9xfOxqT5ll3Q76k0fPvX6tNrfzgC5hnUQoSMK0M0FsRqUt/SMjSfFs+o2higD92sGClIpA26ZOTbtXqNbVTwWqUQ1KkzsRWPTUsuMECjSESlzrgJlj4nWXDSB1rlQkLrZZMZiLrdQJH5JfLIpII+Lq7x7VWtQnGoMJL1a02Ge29oeJAt+CUkJgEQGQFVZEhxc47B/MuecqLTOVPZBt5gWhTCQN6FEMXxwFfn0E/Ei2o3YtIGvMD403Xv1jEe5gfXEAEvBIMoRxRdbzG9/IV2eOQQdARwr5Vp5iEaIuZa0lP4irbylXD5JnPYCFcJxwfL7Dppw8Z6XtSsnuhkqm3sz5QJBzXDKTBMNW8l1snhhg7x2KLUfBOGEgfjhFxet8xdT8N+Ary9wVqbNgL5NtRllDa0XK0Lxpb4spiZKhMWZfiNqLEP9YK/upT5TU08MzpdurW7UXGNY9FjMuxmZOi+r4UQsVuYRSPSZ2WTh5kf+S9uVYIVEKIdW6mK/gEJekV1XX+gkSNYCQ4VUyXNHJiSxTcUaI8FfhFz9ZyZI0nq/SR+fNouwsu0X1oK/0apFneIosPxJ61Kr8Lpkoi0Dq7lGTLMOadarM7IqC0Y8UkZ7+SUZRqfUU=
  email:
    secure: L2wzhR3z4EF0BwB/6ppY7pN2AtHHdIibUahNxSzK9zzHD5nfwor8YxG3Iavu341EmBCXLDUYWkRFU92bq9XQK+SovQVnuyqcuagvKu2OGNCyqHPucLN6OCMNopBN4y5eacZWeCdzW+IJDTvBI+tsedWQszil9rIfTjWq0hqfz9UoqkSHhrNEbxtd/ZVyCNfx7VB6agxdUWmLlLg7E4ipLJdJjQJxYOgKFeL2c+ecJrYgzvOkNhqHlkTD1dtiGkb1mZJHdL2kGfr9e1/347zuC13shhrUy3g+dhviMhOzsDT+tV9HA6GyGRfIeQdzoequPcO7/hEHAo0vUa1CouC5DWAfmM2T9jhUOO8Xo3YDpRe/e54vLzzR5OTy71NnfMjarlX7IIrdnLAf1nl3lXpcOyuDIkJA3tV8oNwX8pHjB+y9fEeFmbKOol6thvXWfHLa49afQ+nlK5yL2ALTv8JYZexedd91NSN3HQY1CN5Ig9h6FGfKAFKNmYCfXF5ADEGV5s7BOvgkrGqqcI95t9j1Yhg6y4z1oosqDkHoAxKZO1Y0ATOyVpeJyq/kGsE/Vm2BoDlVRUQ+CEIcNkDNBKqF+aZaZqtlZ2UBnxv76E6ava1L2noOsB2LkfW7iBYVUsZYLROJzlro3SLwBYQqbFOlZh1xeWgCu5o0rb64xrqFGQQ=
